version: "3.7"

services:
  api:
    container_name: "teste_api"
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app/src
    links:
      - luan-db

  luan-db:
    image: postgres:13.4-buster
    container_name: "${DB_HOST-db}"
    hostname: "${DB_HOST}"
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_BASE}
    ports:
      - "5432:5432"